moving from username and password to tokens
py-pkgs/py-pkgs pull request #140
Opened 2024-01-09 23:53 UTC by ttimbers

Addesses #137

2024-01-09 23:58 UTC, TomasBeuzen approved these changes
LGTM - thanks for doing this 👍

2024-01-10 00:01 UTC, TomasBeuzen requested changes
Just missing a closing parenthesis at: "(e.g., [LastPass](https://www.lastpass.com/) or [1Password](https://1password.com/)**)**"

2024-01-10 04:21 UTC, ttimbers commented
Thanks for the review!

2024-01-10 04:24 UTC, TomasBeuzen approved these changes

2024-01-10 04:29 UTC, merged