working on updating cd
py-pkgs/py-pkgs pull request #143
Opened 2024-01-21 07:56 UTC by ttimbers

This PR is a work in progress, and is trying to update the book's description of cd using python-semantic-release. Most of the discussion of the needed changes are here: https://github.com/py-pkgs/py-pkgs-cookiecutter/pull/71

2024-01-21 22:51 UTC, TomasBeuzen requested changes

2024-01-21 22:51 UTC, TomasBeuzen commented on py-pkgs/08-ci-cd.ipynb
> +    "In **{numref}`07:Automatic-version-bumping`**, we used the `semantic-release version` to get PSR to automatically update our version based on keywords it finds in all the commit messages that ha
Missing word discuss/show: at "... Later, we will _discuss_ a second PSR Github..."

2024-01-21 22:51 UTC, TomasBeuzen commented on py-pkgs/08-ci-cd.ipynb
> +    "To do this we will a second GitHub action from PSR, [python-semantic-release/upload-to-gh-release@main](https://github.com/python-semantic-release/upload-to-gh-release). \n",
Missing word "use" : "To do this we will _use_ a second GitHub action from PSR..."

2024-01-21 22:51 UTC, TomasBeuzen commented on py-pkgs/08-ci-cd.ipynb
> +    "However, PSR\\index{versioning!Python Semantic Release}\\index{Python Semantic Release} can do more than this! In fact, it can do almost the steps we list above (the one step it will not do is p
Missing word "all": "...it can do almost _all_ the steps we list above..."

2024-01-21 22:51 UTC, TomasBeuzen commented on py-pkgs/08-ci-cd.ipynb
> +    "- name: Use Python Semantic Release to prepare release\n",
lines from `id` down need to be de-indented, here's the current render:

![image](https://github.com/py-pkgs/py-pkgs/assets/40379073/4c10ad85-90b8-4d29-8b7b-8ea4493995b1)

2024-01-21 22:58 UTC, TomasBeuzen commented on py-pkgs/08-ci-cd.ipynb
> +    "            pycounts_tt_2024\n",
`pycounts_tt_2024` -> `pycounts`

2024-01-22 05:22 UTC, ttimbers commented
Great job catching all these typos @TomasBeuzen 🤩 !!! Really really appreciate the review, especially on the weekend! Going to 🚢 it!

2024-01-22 05:22 UTC, merged